# 공통 변수
seed : 42
mode : train
device : cpu
model_code : autoencoder
topk : 5
defaults:

  - data : data_source
  - dataset : autoencoder
  - dataloader : pytorch_dataloader
  - optimizer : sgd
  - criterion : mse
  - model: autoencoder
  - runner : autoencoder
  - generator : autoencoder
